version: 0.2
env:
  LOGIN: a3a2a6dce684dedb26461358d162f522bbb251cc
  HOST: https://eco-dev-use1-sonarqube.contentservice.net/
  Project: python-sonarqube-testing
# env:
#   secrets-manager:
#     LOGIN: dev/sonar:sonartoken
#     HOST: dev/sonar:host
#     Project: dev/sonar:project
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt -y update && apt -y upgrade
      - apt install -y jq
  pre_build:
    commands:
      - mkdir downloads -p && cd downloads
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
      - export PATH="$PATH:/opt/sonar-scanner/bin"
  build:
    commands:
      - cd ../
      - sonar-scanner -Dsonar.projectKey=$Project -Dsonar.sources=. -Dsonar.host.url=$HOST -Dsonar.login=$LOGIN
      - sleep 5
      - curl -u $LOGIN https://eco-dev-use1-sonarqube.contentservice.net/api/qualitygates/project_status?projectKey=$Project > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
